name: CI

on: [push, pull_request]

jobs:
  test-build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: pnpm/action-setup@v2
        with:
          version: 7.14.1
      - run: pnpm install
      - run: pnpm test
      - run: pnpm build
